// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoor3lrbYgJR-IYixXK_adFvn_9fpEvM',
    appId: '1:592866601855:web:09105fe51fec1a5930884a',
    messagingSenderId: '592866601855',
    projectId: 'projectalihjenjangd4pnp',
    authDomain: 'projectalihjenjangd4pnp.firebaseapp.com',
    storageBucket: 'projectalihjenjangd4pnp.appspot.com',
    measurementId: 'G-SJ1MPXRBTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn3HJ_YnFbLUiqoAryjgrAgrEqy277PXs',
    appId: '1:592866601855:android:e9c494bb4117ae1930884a',
    messagingSenderId: '592866601855',
    projectId: 'projectalihjenjangd4pnp',
    storageBucket: 'projectalihjenjangd4pnp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYrSz0TtYh30f-zUf0dCXIoIavYXth_U',
    appId: '1:592866601855:ios:f244a38dcf7bc5b530884a',
    messagingSenderId: '592866601855',
    projectId: 'projectalihjenjangd4pnp',
    storageBucket: 'projectalihjenjangd4pnp.appspot.com',
    iosBundleId: 'com.udacoding.mobileAlihjenjangd4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKYrSz0TtYh30f-zUf0dCXIoIavYXth_U',
    appId: '1:592866601855:ios:f7e310d6de02fde830884a',
    messagingSenderId: '592866601855',
    projectId: 'projectalihjenjangd4pnp',
    storageBucket: 'projectalihjenjangd4pnp.appspot.com',
    iosBundleId: 'com.udacoding.mobileAlihjenjangd4.RunnerTests',
  );
}
